getting_started/config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :articles do
    resources :comments
  end

  resources :articles
  root :to => 'articles#index'

end

getting_started/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, 
		                length: { minimum: 5 }
  validates :date_published, presence: { message: "format is YYYY-MM-DD" }



  validates :image_,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }

  has_attached_file :image_, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
end

getting_started/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

getting_started/app/models/user.rb
class User < ActiveRecord::Base
end

getting_started/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

getting_started/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "chris", 
  password: "asdf", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
    #render plain: params[:article].inspect
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:image_, :title, :text, :date_published)
    end
end

getting_started/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "chris", 
  password: "asdf", only: :destroy

  def index
    @comments = Comment.all
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

getting_started/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # After save, send welcome_email
        UserMailer.welcome_email(@user).deliver_later

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

getting_started/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

getting_started/app/helpers/application_helper.rb
module ApplicationHelper
end

getting_started/app/helpers/articles_helper.rb
module ArticlesHelper
end

getting_started/app/helpers/comments_helper.rb
module CommentsHelper
end

getting_started/app/helpers/users_helper.rb
module UsersHelper
end

getting_started/app/helpers/welcome_helper.rb
module WelcomeHelper
end

getting_started/app/views/articles/_article.html.slim
br
/= link_to article, class: 'pic-link' do
  = image_tag article.image_.url(:medium)
br
table
  tr
    th Title
    th Text
    th colspan="2"
  - @articles.each do |article|
  tr
    td = article.title
    td = article.text
    td = link_to 'Show', article_path(article)
    td = link_to 'Edit', edit_article_path(article)
    td = link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?'}

getting_started/app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    .error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |  prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |msg|
          li
            = msg
  p
    = f.label :title
    br
    = f.text_field :title, :class => 'title'
  p
    = f.label :text
    br
    = f.text_area :text
  p
    = f.label :date_published
    br
    = f.date_field :date_published, :maxlength => 10, :placeholder => "YYYY-MM-DD", :class => 'datepicker'


    /:data => {:provide => "datepicker"}
  p
    = f.label :image_
    br
    = f.file_field :image_
  p
    = f.submit

p#test_id
  | Testtesttesttest

getting_started/app/views/articles/edit.html.slim
h1 Edit article
= render 'form'
= link_to 'Back', articles_path

getting_started/app/views/articles/index.html.slim
h1 Listing articles
= link_to 'New article', new_article_path
br

br
table
  tr
    th Title
    th Text
    th colspan="2"
  - @articles.each do |article|
	tr
	  td = article.title
	  td = article.text
	  td = link_to 'Show', article_path(article)
	  td = link_to 'Edit', edit_article_path(article)
	  td = link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?'}
br

h2 Comments

/- @articles.each do |article|
  = render article.comments

table
  tr
    th Commenter
    th Body
    th Article
  - @articles.each do |article|
    - article.comments.each do |comment|
      tr
        td
          = comment.commenter
        td
          = comment.body
        td
          = article.title
  /tr
    = render 'comments/commentinfo', locals: {comments: article.comments}



/= render @articles

getting_started/app/views/articles/new.html.slim
h1 New article
= render 'form'
= link_to 'Back', articles_path

getting_started/app/views/articles/show.html.slim
p
  strong Title: 
  = @article.title
p
  strong Text: 
  = @article.text

p
  strong Date: 
  = @article.date_published

= image_tag @article.image_.url(:medium)

h2 Comments
= render @article.comments

h2 Add a comment:
= render 'comments/form'

= link_to 'Edit', edit_article_path(@article)
= ' | '
= link_to 'Back', articles_path

getting_started/app/views/comments/_comment.html.slim
p
  strong Commenter: 
  = comment.commenter
p
  strong Comment: 
  = comment.body
p
  = link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }

getting_started/app/views/comments/_commentinfo.html.slim
- comments.each do |comment|
  td 
    = comment.commenter
  td 
    = comment.body
  td 
    = "hej!!"

getting_started/app/views/comments/_form.html.slim
= form_for([@article, @article.comments.build]) do |f|
  p
    = f.label :commenter
    br
    = f.text_field :commenter
  p
    = f.label :body
    br
    = f.text_area :body
  p
    = f.submit

getting_started/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

getting_started/app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :login
    = f.text_field :login
  .actions = f.submit

getting_started/app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

getting_started/app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th Login
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.login
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

getting_started/app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

getting_started/app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email
p
  strong Login:
  = @user.login

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path

getting_started/app/views/welcome/index.html.slim
h1 Hello, World!
p 
  | Welcome to 
  = link_to 'My Blog', controller: 'articles'